// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAoWbE3xJG11IISpNzorn3hveH-YQaNio',
    appId: '1:1044422992602:web:18159509857ad98d2d3be3',
    messagingSenderId: '1044422992602',
    projectId: 'privatenotes-sujan',
    authDomain: 'privatenotes-sujan.firebaseapp.com',
    storageBucket: 'privatenotes-sujan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEi6ih2_witL-KaggG-yXKXdf8U7arGEk',
    appId: '1:1044422992602:android:b39858bb8ed3a6462d3be3',
    messagingSenderId: '1044422992602',
    projectId: 'privatenotes-sujan',
    storageBucket: 'privatenotes-sujan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_XrVtpd1bBtRoRwRJqNwgIr1HaPymOLY',
    appId: '1:1044422992602:ios:1624b2a16b14f8cb2d3be3',
    messagingSenderId: '1044422992602',
    projectId: 'privatenotes-sujan',
    storageBucket: 'privatenotes-sujan.appspot.com',
    iosBundleId: 'com.sujanshrestha.privatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_XrVtpd1bBtRoRwRJqNwgIr1HaPymOLY',
    appId: '1:1044422992602:ios:1624b2a16b14f8cb2d3be3',
    messagingSenderId: '1044422992602',
    projectId: 'privatenotes-sujan',
    storageBucket: 'privatenotes-sujan.appspot.com',
    iosBundleId: 'com.sujanshrestha.privatenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAoWbE3xJG11IISpNzorn3hveH-YQaNio',
    appId: '1:1044422992602:web:54d7e2b3e60249452d3be3',
    messagingSenderId: '1044422992602',
    projectId: 'privatenotes-sujan',
    authDomain: 'privatenotes-sujan.firebaseapp.com',
    storageBucket: 'privatenotes-sujan.appspot.com',
  );
}
